version: '3.1'
services:
  postgres_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: Naruzami
      POSTGRES_PASSWORD: master
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    volumes:
      - pgdata_next:/var/lib/postgresql/data

volumes:
  pgdata_next: